### ISSUE TITLE
flex-center utility class?

### ISSUE THREAD

**Issue by dperrera** [tachyons-css/tachyons-flexbox#12]
I use Flexbox a bunch and a use case that I find myself running into quite frequently is centering an element in a box. This is a piece of cake with Flexbox and Tachyons but it can be a little noisy:

`<div class="flex items-center justify-center">`

I wonder if it would be nice to have a `flex-center` utility class that bundles `items-center` and `justify-center`:

```css
.flex-center {
  align-items: center;
  justify-content: center;
}
```
`flex-center` feels similar in spirit to the `center` class. I'm happy to help implement this if it sounds interesting.
